spring:
  config:
    import: optional:configserver:http://ims-config-server
  cloud:
    config:
      enabled:  true
      retry:
        max-attempts: 3

# enable eureka & disable kubernetes
eureka:
  client:
    enabled: false
