spring:
  application:
    name: ims-plp-services
  datasource:
    url: jdbc:postgresql://localhost:5432/test2
    username: postgres
    password: 123456
  flyway:
    schemas: ims_plp_service_db
    default : ims_plp_service_db
    enabled: true
    locations: classpath:db/migration
  cloud:
    compatibility-verifier:
      enabled: false

feign:
  httpclient:
    enabled: true

ssl:
  key-store: classpath:certificates/stc-qa-keystore.p12
  key-store-password: WUhjaVKrQjDc6j8Bdc9X
  key-store-type: p12

kafka:
  bootstrap-servers: localhost:9092
  topic:
    product-updates: product-topic