spring:
  application:
    name: ims-plp-services
  datasource:
    url: jdbc:postgresql://localhost:5432/test2
    username: postgres
    password: 123456
  flyway:
    schemas: ims_plp_service_db
    default : ims_plp_service_db
    enabled: true
    locations: classpath:db/migration/local
  cloud:
    compatibility-verifier:
      enabled: false

feign:
  httpclient:
    enabled: true

ssl:
  key-store: classpath:certificates/stc-qa-keystore.p12
  key-store-password: WUhjaVKrQjDc6j8Bdc9X
  key-store-type: p12

kafka:
  bootstrap-servers: localhost:9092
  topic:
    product-updates: product-topic
    product-updates-ddl: product-topic-ddl

#logging
logging:
  config: "classpath:logback/logback-spring-dev.xml"
  file:
    name: ${spring.application.name}
    path: /opt/logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: "30MB"
      max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:SSS} [%thread] [%-5level] %logger{55} [%X{traceId},%X{userId}] [%X{sourceName},%X{serviceNameUrl}] : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{55} [%X{traceId},%X{userId}] [%X{sourceName},%X{serviceNameUrl}] : %msg%n"
  level:
    net:
      ttddyy:
        dsproxy:
          listener: DEBUG
    root: info
    org:
      apache.poi: warn
      hibernate:
        SQL: ERROR
      springframework:
        web: error
        security: debug
        scheduling: debug

product:
  service:
    url: localhost:9050

stc:
  sync:
#    url: https://sandbox.api.stc.com.sa:9512/s-tmf/productCatalogManagement/consumer/v1
    url: localhost:8081/stc
